language: php

php:
  - 7.0
  - 7.2

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - composer install

script: vendor/bin/phpunit --configuration phpunit.xml

notifications:
  email:
    - yosmellopez@gmail.com